# Generated by Django 4.2.30 on 2026-04-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('season', models.PositiveSmallIntegerField(help_text='Season year, e.g. 2025')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Completed', 'Completed')], default='Upcoming', max_length=15)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('max_drivers', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'championships',
                'ordering': ['-season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='championships.championship')),
            ],
            options={
                'db_table': 'championship_entries',
                'ordering': ['-points'],
            },
        ),
    ]
