# Generated by Django 4.2.30 on 2026-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Attended', 'Attended')], default='Pending', max_length=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('race_type', models.CharField(choices=[('Practice', 'Practice'), ('Qualifying', 'Qualifying'), ('Grand Prix', 'Grand Prix')], default='Practice', max_length=20)),
                ('skill_level', models.CharField(choices=[('All', 'All Levels'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='All', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_mins', models.PositiveSmallIntegerField(default=15)),
                ('max_drivers', models.PositiveSmallIntegerField(default=12)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Full', 'Full'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('track_name', models.CharField(default='DRS Lane Main Circuit', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'races',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('best_lap_ms', models.PositiveIntegerField(blank=True, help_text='Best lap time in milliseconds', null=True)),
                ('total_time_ms', models.PositiveIntegerField(blank=True, help_text='Total race time in milliseconds', null=True)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('fastest_lap', models.BooleanField(default=False)),
                ('dnf', models.BooleanField(default=False, verbose_name='Did Not Finish')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'race_results',
                'ordering': ['position'],
            },
        ),
    ]
