# Generated by Django 4.2.30 on 2026-04-07 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('races', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('championships', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.driverprofile'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.race'),
        ),
        migrations.AddField(
            model_name='race',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='championships.championship'),
        ),
        migrations.AddField(
            model_name='race',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_races', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.driverprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='races.race'),
        ),
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together={('race', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('driver', 'race')},
        ),
    ]
