# Generated by Django 4.2.30 on 2026-04-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_passwordresettoken_and_more'),
        ('races', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Promoted', 'Promoted'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='users.driverprofile')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='races.race')),
            ],
            options={
                'db_table': 'race_waitlist',
                'ordering': ['position'],
                'unique_together': {('driver', 'race')},
            },
        ),
    ]
