# Generated by Django 4.2.30 on 2026-04-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Race', 'Race'), ('Skill', 'Skill'), ('Social', 'Social'), ('Milestone', 'Milestone')], default='Race', max_length=15)),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('points_bonus', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='DriverAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.achievement')),
            ],
            options={
                'db_table': 'driver_achievements',
                'ordering': ['-earned_at'],
            },
        ),
    ]
