# Generated by Django 4.2.30 on 2026-04-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverachievement',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.driverprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='driverachievement',
            unique_together={('driver', 'achievement')},
        ),
    ]
